version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  redis:
    container_name: redis
    image: redis:7.0-alpine
    volumes:
      - redis-volume:/data
    ports:
      - "6379:6379"
  mongo:
    container_name: mongo
    image: mongo:6.0.3
    volumes:
      - mongo-volume:/data/db
      - mongo-volume:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-11-17T23-20-09Z
    command: server -C /etc/minio --address ":9000" --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - minio-volume:/data
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"
  adminer:
    container_name: adminer
    image: adminer:4.8.1-standalone
    ports:
      - "8015:8080"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.0-apache
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8020:80"
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    environment:
      MH_STORAGE: maildir
    ports:
      - "1025:1025"
      - "8025:8025"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "8030:15672"
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - nginx-volume:/usr/share/nginx/html
  openldap:
    container_name: openldap
    image: bitnami/openldap:2.6.4
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: password
      LDAP_USERS: 'user1,user2'
      LDAP_PASSWORDS: 'password,password'
    volumes:
      - openldap-volume:/bitnami/openldap
volumes:
  mysql-volume:
  redis-volume:
  mongo-volume:
  minio-volume:
  postgres-volume:
  rabbitmq-volume:
  nginx-volume:
  nginx-conf-volume:
  openldap-volume:
